[discord]
token = "bot_token"
guild_id = "id"
verify_channel = "id"
reaction_channels = ["id", "id2"]
thread_react_channels = ["id", "id2"]
verified_role = "id"
moderator_role = "id"
admin_role = "id"
teacher_role = "id"
helper_role = "id"
pin_vote_count = 5

[database]
host = "localhost"
port = "5432"
user = "user"
password = "password"
dbname = "dbname"
slave = false

[email]
verify_domain = "mail.tld"
address = "smtp.mail.tld"
port = 465
ssl = true
user = "user@mail.tld"
password = "password"

[log]
path = "cunim.log"

[utils]
url_fetch_script = "utils/url_fetch.py"