[discord]
token = "bot_token"
guild_id = "id"
verify_channel = "id"
verified_role = "id"
moderator_role = "id"
admin_role = "id"

[database]
host = "localhost"
port = "5432"
user = "user"
password = "password"
dbname = "dbname"

[email]
verify_domain = "mail.tld"
address = "smtp.mail.tld"
port = 465
ssl = true
user = "user@mail.tld"
password = "password"

[log]
path = "cunim.log"