[discord]
token = "bot_token"
verify_channel = "id"
reaction_channels = ["id", "id2"]
thread_react_channels = ["id", "id2"]
dedupe_channels = ["id", "id2"]
confession_channel = "id"
verified_role = "role name"
moderator_role = "role name"
admin_role = "role name"
teacher_role = "role name"
helper_role = "role name"
pin_vote_count = 5

[database]
host = "localhost"
port = "5432"
user = "user"
password = "password"
dbname = "dbname"

[email]
verify_domain = "mail.tld"
address = "smtp.mail.tld"
port = 465
ssl = true
user = "user@mail.tld"
password = "password"

[log]
path = "cunim.log"

[utils]
mason = false
url_fetch_script = "utils/url_fetch.py"
openweather_token = "xxxxxxxxxxxxx"
[utils.uploader]
site = 0 # 0 - disable, 1 - catbox, 2 - linx, 3 - lolisafe
catbox_hash = "xxxxxxxxxxxxxxxx"
linx_url = "https://example.com"
loli_url = "https://example.com"
loli_token = "xxxxxxxxxxxxxxxx"
